version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/mern-starter # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:8.10 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands 
      - checkout # special step to check out source code to working directory
      - run:
          name: prepare-config
          command: echo "{\"test\": {\"username\": \"postgres\",\"password\": null,\"database\": \"seneca_database_test\",\"host\": \"127.0.0.1\",\"dialect\": \"postgres\"}}" > src/config/config.json
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm-wee
          command: npm install
      - run: # run tests
          name: test
          command: npm test
      - run: # run check style
          name: check-style
          command: npm run check-style
      - run: # run coverage report
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts: # special step to save test results as as artifact
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results: # special step to upload test results for display in Test Summary
          path: test-results.xml
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    